### PR TITLE
(207) Tidy up confirmation page

### PR DESCRIPTION
**Pull request by leeky**
Remove 'Summary' and 'Problem' headings, as well as the description of
the problem the user entered.

### CODE REVIEW

**Comment by leeky** [comment]
Rebased.

**Comment by dgmstuart** [comment]
Rebased

**Review by dgmstuart — COMMENTED** [review]
Code looks good - not able to test through the app yet because we can't get through to the confirmation page: the endpoints are out of sync: some have /v1, others don't.

**Comment by dgmstuart** [comment]
rebased

**Review by dgmstuart — APPROVED** [review]
LGTM 🚢

**Pull request merged**
