### PR TITLE
(218) Tweaks to content

### PR DESCRIPTION
**Pull request by leeky**
Updates to content as per the tweaks suggested by our content designer.

### CODE REVIEW

**Comment by JasonEwins** [comment]
@leeky please can you revise the following:

1) question-communal_problem: please amend question from 'communal grounds' to 'communal area' for consistency

2) question-bathroom_problem: please amend 'Basin' to 'Basin / Sink'

3) describe_repair-inside_light_fitting: for consistency please append 'to the light fitting' to 'whether there is any obvious damage....' 

4) page-smoke_detector: I don't feel we need to display the gas, electric or water supply contact numbers here as they're not relevant

5) page-toilet_unblock_info: please revise: 
a) Heading to read 'Common fixes - unblock toilet'
b) Subheading style to be consistent with other video tutorial pages 
c) Amend text to 'Watch this short video for advice for advice on how to unblock your toilet' (as per page-replace_lightbulb)

6) question-heating_problem: please include option for 'I have no heating' which links to page-heating_repairs

7) question-outside_problem: please append 'or overflowing' to 'A drain is blocked' option (**may have been updated already**)

**Comment by JasonEwins** [comment]
screenshots don't include 'unblock a sink' tutorial video

**Comment by leeky** [comment]
@JasonEwins I've added a page for the 'unblocking a sink' tutorial video

page-unblock_sink

After pressing 'continue' above:

describe_repair-inside_sink_blocked

**Comment by leeky** [comment]
@JasonEwins  -

### question-communal_problem: please amend question from 'communal grounds' to 'communal area' for consistency

question-communal_problem

### question-bathroom_problem: please amend 'Basin' to 'Basin / Sink'

question-bathroom_problem

### describe_repair-inside_light_fitting: for consistency please append 'to the light fitting' to 'whether there is any obvious damage....'

describe_repair-inside_light_fitting

### page-smoke_detector: I don't feel we need to display the gas, electric or water supply contact numbers here as they're not relevant

page-smoke_detector

### page-toilet_unblock_info: please revise:

a) Heading to read 'Common fixes - unblock toilet'
b) Subheading style to be consistent with other video tutorial pages
c) Amend text to 'Watch this short video for advice for advice on how to unblock your toilet' (as per page-replace_lightbulb)

page-toilet_unblock_info

### question-heating_problem: please include option for 'I have no heating' which links to page-heating_repairs

question-heating_problem

... which links to...

page-heating_repairs


### question-outside_problem: please append 'or overflowing' to 'A drain is blocked' option (may have been updated already)

question-outside_problem

**Review by lexijax — APPROVED** [review]
LGTM. Can't spot anything obviously wrong with anything here.

**Pull request merged**
