### PR TITLE
(81) Contact page

### PR DESCRIPTION
**Pull request by leeky**
Dummy form for collecting the user's contact details, as per the prototype.

From: `/contact-details`

contact-details

### CODE REVIEW

**Comment by dgmstuart** [comment]
Since we're doing the 'callback' option, this needs to follow the 'Unknown repair' option from the prototype, with fields for the callback time:

screen shot 2017-10-02 at 16 25 37

**Review by dgmstuart — CHANGES_REQUESTED** [review]
Needs fields for callback times

**Comment by leeky** [comment]
@dgmstuart I've added the missing fields to the form:

contact-details-revised

**Review by dgmstuart — APPROVED** [review]

**Comment by dgmstuart** [comment]
LGTM 👍

**Pull request merged**
